export {DeletedMarkData} from './data/DeletedMarkData'
export type {IExternalData} from './interfaces/IExternalData'
export {externalDataSymbol} from './const/externalDataSymbol'
export {DeletionRule} from './rules/DeletionRule'
export {EntityDeletionRule} from './rules/EntityDeletionRule'